name: Build com Vite

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🧱 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔨 Rodar build do Vite
        run: npm run build

      - name: 📤 Salvar pasta dist como artefato
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
