name: Deploy Hostinger via SFTP (somente build)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🧱 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔨 Rodar build do Vite
        run: npm run build

      - name: 🚀 Enviar build para a Hostinger (somente pasta dist/)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: ftp
          port: ${{ secrets.SFTP_PORT }}
          local-dir: dist/
          server-dir: public_html/
